### ISSUE TITLE
module std.stream is deprecated

### ISSUE THREAD

**Issue by zafer06** [cruisercoder/dstddb#2]
Hi,
Clone the project and I try to run dub build but I get this error. 

`src/std/database/resolver.d(8,8): Deprecation: module std.stream is deprecated - It will be removed from Phobos in October 2016. If you still need it, go to https://github.com/DigitalMars/undeaD
`

**Comment by cruisercoder** [comment]
I think that's just a warning, but I also just committed a fix for that.  Let me know if you encounter other issues.

**Comment by zafer06** [comment]
Thank you Erik. I need PostgreSQL support, I hope that happens soon. I use ddb now.
